version: '3.3'

services:
  psql:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=aboba
      - DB_CONNECT_RETRY=20
      - DB_POOL_SIZE=15
    networks:
      - app_network
  api:
    image: 'dima/product:0.0.11'
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - psql
      - kafka
    entrypoint: "python main.py"
  ml:
    image: dima/ml:0.0.3
    ports:
      - "8001:8001"
    networks:
      - app_network
    depends_on:
      - kafka
  client:
    image: "dima/client:0.0.11"
    ports:
      - "3000:3000"
    networks:
      - app_network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app_network
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "embedding_requests:1:1,embedding_responses:1:1"
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - app_network

networks:
  app_network: