version: '3.3'

services:
  psql:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=aboba
      - DB_CONNECT_RETRY=20
      - DB_POOL_SIZE=15
