"""Initial migration

Revision ID: 36b13b325680
Revises: 
Create Date: 2025-01-07 18:49:51.325241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b13b325680'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('embedding', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__products'))
    )
    op.create_index(op.f('ix__products__id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix__products__name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__products__name'), table_name='products')
    op.drop_index(op.f('ix__products__id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
